# Generated by Django 2.1.7 on 2019-04-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('howlong', models.SmallIntegerField()),
                ('howmany', models.SmallIntegerField()),
                ('salepercent', models.SmallIntegerField()),
                ('start_time', models.FloatField(blank=True)),
                ('end_time', models.FloatField(blank=True)),
                ('used', models.SmallIntegerField(default=0)),
                ('left', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_url', models.URLField(max_length=350)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Coupon')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_picture', models.URLField(max_length=350)),
                ('large_picture', models.URLField(max_length=350)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='product.ProductPicture'),
        ),
    ]
