# Generated by Django 2.1.7 on 2019-03-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='left',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.FloatField(default=1553026309.4906201),
        ),
        migrations.AlterField(
            model_name='product',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Coupon'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(blank=True, null=True, to='product.ProductPicture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
