# Generated by Django 2.1.7 on 2019-03-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190319_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.FloatField(default=1553026327.8023293),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='product.ProductPicture'),
        ),
    ]
